### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by jianwwpro** [ceridwen-com/lcfserver#1]
/Users/wangjianwu/Documents/WorkSpace/git/lcfserver/lcfserver-core/src/main/java/com/ceridwen/lcf/server/core/exceptions/EXC00_LCF_Exception.java:[31,27] 找不到符号
[ERROR]   符号:   类 MessageType
[ERROR]   位置: 程序包 org.bic.ns.lcf.v1_0

**Comment by mdovey** [comment]
This was due to ongoing changes in the underlying LCF xml schema. Now that 1.1.0 has been released, this has been updated to compile against the 1.1 schema.
